#!/usr/bin/env bash
# displays information about a domain and its subdomain

func() {
    echo $(dig "$1" | grep -A1 "ANSWER SECTION:" | tail -n 1)
}

if [ $# -eq 2 ]; then
    out=$(func "$1")
    A_REC=$(echo "$out" | awk -F " " '{print $4}')
    DEST=$(echo "$out" | awk -F " " '{print $5}')
    echo "The subdomain $2 is a $A_REC record and points to $DEST"
fi
