#!/usr/bin/env bash
#installs nginx web server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo rm /var/www/html/*.html
sudo touch index.html
sudo chmod 006 index.html
sudo echo "Holberton School" > index.html
sudo service nginx start
