#!/usr/bin/env bash
# Install nginx load balancer HAProxy
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.6
sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*

sudo echo 'frontend Local_Server
        bind 192.168.1.12:80
        mode http
        default_backend web_servers' >> /etc/haproxy.cfg

sudo echo 'backend web_servers
        mode http
        balance roundrobin
        server 884-web-01 34.74.29.47
        server 884-web-02 35.237.30.103' >> /etc/haproxy.cfg
sudo service haproxy restart
