#!/usr/bin/env bash
# loops from 1 to 10
c=1
while [ "$c" -lt 11 ];
do
	if [ "$c" -eq 4 ]
	then
		echo "bad luck"
	elif [ "$c" -eq 8 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	((c++))
done
