#!/usr/bin/env bash
# displays numbers from 1 to 20
c=1
while [ "$c" -lt 21 ];
do
	echo "$c"
	case "$c" in
	4)
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "bad luck from Italy"
		;;
	esac
	((c++))
done
