#!/usr/bin/env bash
# gives information about holbertonschool file
file="holbertonschool"
if [ -e "$file" ]
then
	echo "holbertonschool file exists"
else
	echo "holbertonschool file does not exist"
	exit 0
fi
if ! [ -s "$file" ]
then
	echo "holbertonschool file is empty"
else
	echo "holbertonschool file is not empty"
fi
if [ -f "$file" ]
then
	echo "holbertonschool is a regular file"
fi
